version: '3.8'

services:
  # Metastore - Using PostgreSQL for Hive Metastore
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    entrypoint: /opt/scripts/postgres-entrypoint.sh
    volumes:
      - postgres_hms_data:/var/lib/postgresql/data
      - ../docker/postgres-hms/postgres-entrypoint.sh:/opt/scripts/postgres-entrypoint.sh
    networks:
      - data_platform_network

  # Hive Metastore Service
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    user: root
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    volumes:
      - ../docker/hive/conf/hive-site.xml.tmpl:/opt/hive/conf/hive-site.xml.tmpl
      - ../docker/hive/hms/hms-setup.sh:/opt/hive/hms-setup.sh
      - ../docker/hive/hms/init-schema.sh:/opt/hive/init-schema.sh
      - hive_data:/opt/hive/data
      - ${PROJECT_ROOT}/data/hive_data/hive-tmp:/tmp/hive
    command: /bin/bash -c "chmod +x /opt/hive/hms-setup.sh && /bin/bash /opt/hive/hms-setup.sh && tail -f /dev/null"
    entrypoint: []
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - data_platform_network
          
  hiveserver2:
    image: apache/hive:3.1.3
    container_name: hiveserver2
    user: root
    depends_on:
      - hive-metastore
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      SERVICE_OPTS: -Dhive.metastore.uris=thrift://hive-metastore:9083
    ports:
      - "10000:10000"  
      - "10002:10002"  
    volumes:
      - ../docker/hive/conf/hive-site.xml.tmpl:/opt/hive/conf/hive-site.xml.tmpl
      - ../docker/hive/conf/core-site.xml.tmpl:/opt/hive/conf/core-site.xml.tmpl
      - ../docker/hive/hs2/hs2-setup.sh:/opt/hive/hs2-setup.sh
      - hive_hs2_data:/opt/hive/data
      - ${PROJECT_ROOT}/data/hive_hs2_data/hive-tmp:/tmp/hive
    entrypoint: ["/bin/bash", "/opt/hive/hs2-setup.sh"]
    networks:
      - data_platform_network

  # hiveserver2:
  #   image: apache/hive:3.1.3
  #   depends_on:
  #     - hive-metastore
  #   container_name: hiveserver2
  #   ports:
  #     - "10000:10000"  # HiveServer2 port
  #     - "10002:10002"  # Thrift port
  #   environment:
  #     SERVICE_NAME: hiveserver2
  #     DB_DRIVER: postgres
  #     SERVICE_OPTS: >-
  #       -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
  #       -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
  #       -Djavax.jdo.option.ConnectionUserName=hms
  #       -Djavax.jdo.option.ConnectionPassword=hms123
  #   volumes:
  #     - ../docker/hive-metastore/lib/postgresql-42.3.1.jar:/opt/hive/lib/postgresql-42.3.1.jar
  #     - hive_hs2_data:/opt/hive/data
  #     - ${PROJECT_ROOT}/data/hive_hs2_data/hive-tmp:/tmp/hive
  #   networks:
  #     - data_platform_network

  # hiveserver2:
  #   image: apache/hive:3.1.3
  #   container_name: hiveserver2
  #   depends_on:
  #     - hive-metastore
  #   ports:
  #     - "10000:10000"  # JDBC port
  #     - "10002:10002"  # Optional (Thrift CLI)
  #   environment:
  #     SERVICE_NAME: hiveserver2
  #     SERVICE_OPTS: >-
  #       -Dhive.metastore.uris=thrift://hive-metastore:9083
  #       -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
  #       -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/${HMS_DB_NAME}
  #       -Djavax.jdo.option.ConnectionUserName=${HMS_DB_USER}
  #       -Djavax.jdo.option.ConnectionPassword=${HMS_DB_PASSWORD}
  #     IS_RESUME: "true"
  #   volumes:
  #     - ../docker/hive-metastore/lib/postgresql-42.3.1.jar:/opt/hive/lib/postgresql.jar:ro
  #     - hive_hs2_data:/opt/hive/data
  #     - ${PROJECT_ROOT}/data/hive_hs2_data:/tmp/hive
  #   networks:
  #     - data_platform_network


volumes:
  postgres_hms_data:
    external: true 
  hive_data:
     external: true
  hive_hs2_data:
     external: true

networks:
  data_platform_network:
    external: true