version: '3.8'

services:
  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   volumes:
  #     - minio_data:/data
  #     - ../docker/minio/init/entrypoint.sh:/entrypoint.sh:ro
  #     - ../docker/minio/init/create-buckets.sh:/create-buckets.sh:ro
  #   ports:
  #     - "${MINIO_API_PORT}:9000"
  #     - "${MINIO_CONSOLE_PORT}:9001"
  #   entrypoint: sh /entrypoint.sh
  #   networks:
  #     - data_platform_network
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}

  minio:
    build:
      context: ./../docker/minio
      dockerfile: Dockerfile
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
    volumes:
      - minio_data:/data
      - ../docker/minio/sample_data/:/sample_data
    networks:
      - data_platform_network

volumes:
  minio_data:
    external: true

networks:
  data_platform_network:
    external: true
