version: '3.8'

services:
  # Metastore - Using PostgreSQL for Hive Metastore
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    entrypoint: /opt/scripts/postgres-entrypoint.sh
    volumes:
      - postgres_hms_data:/var/lib/postgresql/data
      - ../docker/postgres-hms/postgres-entrypoint.sh:/opt/scripts/postgres-entrypoint.sh
    networks:
      - data_platform_network

  # Hive Metastore Service
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    user: root
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    volumes:
      - ../docker/hive/conf/hive-site.xml.tmpl:/opt/hive/conf/hive-site.xml.tmpl
      - ../docker/hive/hms/hms-setup.sh:/opt/hive/hms-setup.sh
      - ../docker/hive/hms/init-schema.sh:/opt/hive/init-schema.sh
      - hive_data:/opt/hive/data
      - ${PROJECT_ROOT}/data/hive_data/hive-tmp:/tmp/hive
    command: /bin/bash -c "chmod +x /opt/hive/hms-setup.sh && /bin/bash /opt/hive/hms-setup.sh && tail -f /dev/null"
    entrypoint: []
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - data_platform_network
          
  hiveserver2:
    image: apache/hive:3.1.3
    container_name: hiveserver2
    user: root
    depends_on:
      - hive-metastore
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      SERVICE_OPTS: -Dhive.metastore.uris=thrift://hive-metastore:9083
    ports:
      - "10000:10000"  
      - "10002:10002"  
    volumes:
      - ../docker/hive/conf/hive-site.xml.tmpl:/opt/hive/conf/hive-site.xml.tmpl
      - ../docker/hive/conf/core-site.xml.tmpl:/opt/hive/conf/core-site.xml.tmpl
      - ../docker/hive/conf/hive-log4j2.properties:/opt/hive/conf/hive-log4j2.properties
      - ../docker/hive/hs2/hs2-setup.sh:/opt/hive/hs2-setup.sh
      - hive_hs2_data:/opt/hive/data
      - ${PROJECT_ROOT}/data/hive_hs2_data/hive-tmp:/tmp/hive
    entrypoint: ["/bin/bash", "/opt/hive/hs2-setup.sh"]
    networks:
      - data_platform_network

volumes:
  postgres_hms_data:
    external: true 
  hive_data:
     external: true
  hive_hs2_data:
     external: true

networks:
  data_platform_network:
    external: true